### PR TITLE
Adding summary to top panel

### PR DESCRIPTION
**Pull request by DavidLozzi**
Found it useful to see some details from the event in the header. We're working on large projects with multiple events possibly triggering within a single click event. This now allows us to see which event we are most interested in and expand to see details. It is configurable through the Options panel.

Before:
image

After:
image

### CODE REVIEW

**Comment by MisterPhilip** [comment]
Thanks for this! I'm out of town at the moment but I'll review when I'm
back.

**Comment by DavidLozzi** [comment]
@MisterPhilip ping 😁

**Comment by MisterPhilip** [comment]
Awesome, thanks for this! I'm going to make a few minor tweaks and then hopefully get it out this weekend :)

**Comment by MisterPhilip** [comment]
@DavidLozzi - this should be rolling out over the next few hours. Thanks again for your hard work on this, I look forward to expanding on it :)

**Pull request merged**
